"use client";
import { Button } from "@/components/ui/button";
import { db } from "@/utils/db";
import { MockInterview } from "@/utils/schema";
import { eq } from "drizzle-orm";
import { Lightbulb, WebcamIcon } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import React, { useEffect, useState } from "react";
import Webcam from "react-webcam";

function Interview({ params }) {
  const [interviewData, setInterviewData] = useState();
  const [webCamEnabled, setWebCamEnabled] = useState(false);
  const path = usePathname();
  const id = path.split("/")[3];
  useEffect(() => {
    console.log(params.interviewId);
    GetInterviewDetails();
  }, []);

  const GetInterviewDetails = async () => {
    const result = await db
      .select()
      .from(MockInterview)
      .where(eq(MockInterview.mockId, params.interviewId));
    setInterviewData(result[0]);
  };
  return (
    <div className="my-10 ">
      <h2 className="font-bold text-2xl">Let's Get Started</h2>
      <br></br>
      <br></br>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
        <div className="p-5 border rounded-lg border-yellow-300 bg-yellow-100">
          <h2 className="text-yellow-500">
            <Lightbulb />
            <strong>Information</strong>
          </h2>
          <h2>
            Enable Webcam and Microphone to start your Ai Mock Interviewer, It
            has 5 questions which you can answer and at last you will get a
            report on the basis of your answer.This response is generated by AI.
            All the best!
          </h2>
        </div>

        <div>
          {webCamEnabled ? (
            <Webcam
              onUserMedia={() => setWebCamEnabled(true)}
              onUserMediaError={() => setWebCamEnabled(false)}
              mirrored={true}
              style={{
                height: 300,
                width: 300,
              }}
            />
          ) : (
            <>
              <WebcamIcon className="h-72 w-full my-7 p-20 bg-secondary rounded-lg border" />
              <Button className="w-full" onClick={() => setWebCamEnabled(true)}>
                Enable Web Cam and Microphone
              </Button>
            </>
          )}
        </div>
      </div>
      <br></br>
      <div className="flex justify-end items-end">
        <Link href={"/dashboard/interview/" + id + "/start"}>
          <Button style={{ backgroundColor: "green", color: "white" }}>
            Start Interview
          </Button>
        </Link>
      </div>
    </div>
  );
}

export default Interview;
